services:
  db:
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-mpmbi_user}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-mpmbi_password}
      POSTGRES_DB: ${POSTGRES_DB:-mpmbi_db}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-mpmbi_user} -d ${POSTGRES_DB:-mpmbi_db}"]
      interval: 10s
      timeout: 5s
      retries: 5

  web:
    image: ghcr.io/${GITHUB_REPOSITORY_LOWER:-upileasta/mpmbi}:${IMAGE_TAG:-latest}
    restart: always
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: postgresql://${POSTGRES_USER:-mpmbi_user}:${POSTGRES_PASSWORD:-mpmbi_password}@db:5432/${POSTGRES_DB:-mpmbi_db}?schema=public
      NEXTAUTH_SECRET: ${NEXTAUTH_SECRET:-}
      NEXTAUTH_URL: ${NEXTAUTH_URL:-}
      AUTH_SECRET: ${NEXTAUTH_SECRET:-}
      AUTH_TRUST_HOST: "true"
    depends_on:
      db:
        condition: service_healthy

volumes:
  postgres_data:
