services:
  db:
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-mpmbi_user}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-mpmbi_password}
      POSTGRES_DB: ${POSTGRES_DB:-mpmbi_db}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    restart: always
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: postgresql://${POSTGRES_USER:-mpmbi_user}:${POSTGRES_PASSWORD:-mpmbi_password}@db:5432/${POSTGRES_DB:-mpmbi_db}?schema=public
      NEXTAUTH_SECRET: ${NEXTAUTH_SECRET:-supersecret}
      NEXTAUTH_URL: ${NEXTAUTH_URL:-http://localhost:3000}
      AUTH_SECRET: ${NEXTAUTH_SECRET:-supersecret}
      AUTH_TRUST_HOST: "true"
      WATCHPACK_POLLING: "true" # Enables HMR to work reliably in Docker
      CHOKIDAR_USEPOLLING: "true" # Enables file watching for Docker
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
    depends_on:
      - db

volumes:
  postgres_data:
